# Generated by Django 5.2.7 on 2025-10-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('Imagen', models.CharField(max_length=255)),
            ],
        ),
    ]
