# Generated by Django 5.2.7 on 2025-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='genero',
            field=models.CharField(default='No definido', max_length=100),
        ),
    ]
